# Config copied from
#  http://www.theautomatedtester.co.uk/blog/2012/using-travis-ci-for-building-and-testing-firefox-addons.html
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python2.7_with_system_site_packages
addons:
  apt:
    packages:
      - libxml2-dev
      - libxml2-utils
      - python-dev
      - libcurl4-openssl-dev
      - python-lxml
      - python-software-properties
      - chromium-browser
virtualenv:
  system_site_packages: true
install:
  - pip install -r test/rules/requirements.txt
  - pip install -r test/chromium/requirements.txt
  - PYCURL_SSL_LIBRARY=openssl pip install --upgrade --force-reinstall --compile pycurl
env:
  - FIREFOX_VERSION=firefox-latest
  - FIREFOX_VERSION=firefox-esr-latest
before_script:
  - sudo apt-get -y install chromium-chromedriver miredo
  - wget -O /tmp/firefox.tar.bz2 'https://download.mozilla.org/?os=linux64&lang=en-US&product='$FIREFOX_VERSION
  - tar xpjf /tmp/firefox.tar.bz2
  - export FIREFOX=$PWD/firefox/firefox
script:
  - sleep 30
  - ping6 -c 10 mnrd.us || true
  - sleep 30
  - ping6 -c 10 mnrd.us || true
  - sleep 240
  - ping6 -c 10 mnrd.us || true
  - curl -s http://myip.mattnordhoff.com/
  - curl -s http://myipv6.mattnordhoff.com/
  - ./test.sh
  - test/travis-ruleset-fetch.sh
sudo: required
dist: trusty
